name: character_viewer
description: Character Viewer.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.3
  get_it: ^7.6.4
  shimmer: ^3.0.0
  logger: ^2.0.2+1
  equatable: ^2.0.5
  injectable: ^2.3.2
  auto_route: ^7.8.4
  flutter_bloc: ^8.1.3
  flutter_tilt: ^2.0.10
  json_annotation: ^4.8.1
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.1
  injectable_generator: ^2.4.1
  auto_route_generator: ^7.3.2

flutter:
  uses-material-design: true
